// Code generated by Slice Machine. DO NOT EDIT.
import FullScreenSlide from './FullScreenSlide/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

// `any` cast required: @prismicio/svelte SliceZoneProps['components'] expects legacy SvelteComponent<> constructors,
// but Svelte 5 exports Component<> — incompatible at the type level even though runtime is fine.
export const components = /** @type {any} */ ({
	full_screen_slide: FullScreenSlide,
	hero: Hero,
	rich_text: RichText
});
