// Code generated by Slice Machine. DO NOT EDIT.

import FullScreenSlide from './FullScreenSlide/index.svelte';
import Hero from './Hero/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	full_screen_slide: FullScreenSlide,
	hero: Hero,
	rich_text: RichText
};
