// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *nav → links*
 */
export interface NavDocumentDataLinksItem {
	/**
	 * text field in *nav → links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * href field in *nav → links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].href
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	href: prismic.LinkField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * links field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavDocumentDataLinksItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

type PageDocumentDataSlicesSlice = HeroSlice | FullScreenSlideSlice | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = NavDocument | PageDocument;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceDefaultPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceDefaultItem {
	/**
	 * button text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * eyebrow field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].body_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body_text: prismic.RichTextField;
}

/**
 * with popup buttons variation for FullScreenSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FullScreenSlideSliceDefaultPrimary>,
	Simplify<FullScreenSlideSliceDefaultItem>
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceEmbedPrimary {
	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * external embed field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.external_embed
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	external_embed: prismic.KeyTextField;
}

/**
 * custom embed variation for FullScreenSlide Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceEmbed = prismic.SharedSliceVariation<
	'embed',
	Simplify<FullScreenSlideSliceEmbedPrimary>,
	never
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceWithVideoPopupPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * button text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	button_text: prismic.RichTextField;

	/**
	 * video embed field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.video_embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video_embed: prismic.EmbedField;
}

/**
 * with video popup variation for FullScreenSlide Slice
 *
 * - **API ID**: `withVideoPopup`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceWithVideoPopup = prismic.SharedSliceVariation<
	'withVideoPopup',
	Simplify<FullScreenSlideSliceWithVideoPopupPrimary>,
	never
>;

/**
 * Slice variation for *FullScreenSlide*
 */
type FullScreenSlideSliceVariation =
	| FullScreenSlideSliceDefault
	| FullScreenSlideSliceEmbed
	| FullScreenSlideSliceWithVideoPopup;

/**
 * FullScreenSlide Shared Slice
 *
 * - **API ID**: `full_screen_slide`
 * - **Description**: FullScreenSlide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSlice = prismic.SharedSlice<
	'full_screen_slide',
	FullScreenSlideSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * vimeo embed field in *Hero → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.video_embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video_embed: prismic.EmbedField;

	/**
	 * loading placeholder field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.loading_placeholder
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	loading_placeholder: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavDocument,
			NavDocumentData,
			NavDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			FullScreenSlideSlice,
			FullScreenSlideSliceDefaultPrimary,
			FullScreenSlideSliceDefaultItem,
			FullScreenSlideSliceEmbedPrimary,
			FullScreenSlideSliceWithVideoPopupPrimary,
			FullScreenSlideSliceVariation,
			FullScreenSlideSliceDefault,
			FullScreenSlideSliceEmbed,
			FullScreenSlideSliceWithVideoPopup,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault
		};
	}
}
