// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *nav → links*
 */
export interface NavDocumentDataLinksItem {
	/**
	 * text field in *nav → links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * href field in *nav → links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[].href
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	href: prismic.LinkField;
}

/**
 * Content for nav documents
 */
interface NavDocumentData {
	/**
	 * links field in *nav*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nav.links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	links: prismic.GroupField<Simplify<NavDocumentDataLinksItem>>;
}

/**
 * nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<NavDocumentData>,
	'nav',
	Lang
>;

type PageDocumentDataSlicesSlice = HeroSlice | FullScreenSlideSlice | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = NavDocument | PageDocument;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceDefaultPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceDefaultItem {
	/**
	 * button text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * eyebrow field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].body_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body_text: prismic.RichTextField;
}

/**
 * with popup buttons variation for FullScreenSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FullScreenSlideSliceDefaultPrimary>,
	Simplify<FullScreenSlideSliceDefaultItem>
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceEmbedPrimary {
	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * external embed field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.external_embed
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	external_embed: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * custom embed variation for FullScreenSlide Slice
 *
 * - **API ID**: `embed`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceEmbed = prismic.SharedSliceVariation<
	'embed',
	Simplify<FullScreenSlideSliceEmbedPrimary>,
	never
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceWithVideoPopupPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * button text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	button_text: prismic.RichTextField;

	/**
	 * body_text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * video embed field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.video_embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video_embed: prismic.EmbedField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * with video popup variation for FullScreenSlide Slice
 *
 * - **API ID**: `withVideoPopup`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceWithVideoPopup = prismic.SharedSliceVariation<
	'withVideoPopup',
	Simplify<FullScreenSlideSliceWithVideoPopupPrimary>,
	never
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceBasicPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;

	/**
	 * button_text_1 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text_1: prismic.KeyTextField;

	/**
	 * button_link_1 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_link_1
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link_1: prismic.LinkField;

	/**
	 * button_text_2 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text_2: prismic.KeyTextField;

	/**
	 * button_link_2 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_link_2
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link_2: prismic.LinkField;
}

/**
 * Basic variation for FullScreenSlide Slice
 *
 * - **API ID**: `basic`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceBasic = prismic.SharedSliceVariation<
	'basic',
	Simplify<FullScreenSlideSliceBasicPrimary>,
	never
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceIconBoxesPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceIconBoxesItem {
	/**
	 * icon field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].icon
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	icon: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * body_text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;
}

/**
 * icon boxes variation for FullScreenSlide Slice
 *
 * - **API ID**: `iconBoxes`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceIconBoxes = prismic.SharedSliceVariation<
	'iconBoxes',
	Simplify<FullScreenSlideSliceIconBoxesPrimary>,
	Simplify<FullScreenSlideSliceIconBoxesItem>
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceTeamsPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceTeamsItem {
	/**
	 * headshot field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].headshot
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	headshot: prismic.ImageField<never>;

	/**
	 * name field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * job title field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body_text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].body_text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	body_text: prismic.RichTextField;
}

/**
 * teams variation for FullScreenSlide Slice
 *
 * - **API ID**: `teams`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceTeams = prismic.SharedSliceVariation<
	'teams',
	Simplify<FullScreenSlideSliceTeamsPrimary>,
	Simplify<FullScreenSlideSliceTeamsItem>
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceHalfPagePrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isImageLeft field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isImageLeft
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isImageLeft: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceHalfPageItem {
	/**
	 * button_text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button_link field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;
}

/**
 * halfPage variation for FullScreenSlide Slice
 *
 * - **API ID**: `halfPage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceHalfPage = prismic.SharedSliceVariation<
	'halfPage',
	Simplify<FullScreenSlideSliceHalfPagePrimary>,
	Simplify<FullScreenSlideSliceHalfPageItem>
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceBigTextPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;

	/**
	 * button_text_1 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text_1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text_1: prismic.KeyTextField;

	/**
	 * button_link_1 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_link_1
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link_1: prismic.LinkField;

	/**
	 * button_text_2 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_text_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text_2: prismic.KeyTextField;

	/**
	 * button_link_2 field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.button_link_2
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link_2: prismic.LinkField;
}

/**
 * big text variation for FullScreenSlide Slice
 *
 * - **API ID**: `bigText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceBigText = prismic.SharedSliceVariation<
	'bigText',
	Simplify<FullScreenSlideSliceBigTextPrimary>,
	never
>;

/**
 * Primary content in *FullScreenSlide → Primary*
 */
export interface FullScreenSlideSliceHalfPageWithButtonOverlaysPrimary {
	/**
	 * background image field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	background_image: prismic.ImageField<never>;

	/**
	 * eyebrow field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.eyebrow
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	eyebrow: prismic.KeyTextField;

	/**
	 * title field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * body text field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * stacks? field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.doesStack
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	doesStack: prismic.BooleanField;

	/**
	 * isBackgroundBlurred field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isBackgroundBlurred
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isBackgroundBlurred: prismic.BooleanField;

	/**
	 * isImageLeft field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isImageLeft
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isImageLeft: prismic.BooleanField;

	/**
	 * isNavLight field in *FullScreenSlide → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: full_screen_slide.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;
}

/**
 * Primary content in *FullScreenSlide → Items*
 */
export interface FullScreenSlideSliceHalfPageWithButtonOverlaysItem {
	/**
	 * button_text field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button_link field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;

	/**
	 * overlay_title field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].overlay_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	overlay_title: prismic.KeyTextField;

	/**
	 * overlay_subtitle field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].overlay_subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	overlay_subtitle: prismic.KeyTextField;

	/**
	 * overlay_body field in *FullScreenSlide → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: full_screen_slide.items[].overlay_body
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	overlay_body: prismic.RichTextField;
}

/**
 * halfPageWithButtonOverlays variation for FullScreenSlide Slice
 *
 * - **API ID**: `halfPageWithButtonOverlays`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSliceHalfPageWithButtonOverlays = prismic.SharedSliceVariation<
	'halfPageWithButtonOverlays',
	Simplify<FullScreenSlideSliceHalfPageWithButtonOverlaysPrimary>,
	Simplify<FullScreenSlideSliceHalfPageWithButtonOverlaysItem>
>;

/**
 * Slice variation for *FullScreenSlide*
 */
type FullScreenSlideSliceVariation =
	| FullScreenSlideSliceDefault
	| FullScreenSlideSliceEmbed
	| FullScreenSlideSliceWithVideoPopup
	| FullScreenSlideSliceBasic
	| FullScreenSlideSliceIconBoxes
	| FullScreenSlideSliceTeams
	| FullScreenSlideSliceHalfPage
	| FullScreenSlideSliceBigText
	| FullScreenSlideSliceHalfPageWithButtonOverlays;

/**
 * FullScreenSlide Shared Slice
 *
 * - **API ID**: `full_screen_slide`
 * - **Description**: FullScreenSlide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullScreenSlideSlice = prismic.SharedSlice<
	'full_screen_slide',
	FullScreenSlideSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * vimeo embed field in *Hero → Primary*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.video_embed
	 * - **Documentation**: https://prismic.io/docs/field#embed
	 */
	video_embed: prismic.EmbedField;

	/**
	 * loading placeholder field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.loading_placeholder
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	loading_placeholder: prismic.ImageField<never>;

	/**
	 * body_text field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.body_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	body_text: prismic.KeyTextField;

	/**
	 * isNavLight field in *Hero → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.primary.isnavlight
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	isnavlight: prismic.BooleanField;

	/**
	 * button text field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	button_text: prismic.KeyTextField;

	/**
	 * button_link field in *Hero → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
	/**
	 * Content field in *RichText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Lorem ipsum...
	 * - **API ID Path**: rich_text.primary.content
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<RichTextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<'rich_text', RichTextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			NavDocument,
			NavDocumentData,
			NavDocumentDataLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			FullScreenSlideSlice,
			FullScreenSlideSliceDefaultPrimary,
			FullScreenSlideSliceDefaultItem,
			FullScreenSlideSliceEmbedPrimary,
			FullScreenSlideSliceWithVideoPopupPrimary,
			FullScreenSlideSliceBasicPrimary,
			FullScreenSlideSliceIconBoxesPrimary,
			FullScreenSlideSliceIconBoxesItem,
			FullScreenSlideSliceTeamsPrimary,
			FullScreenSlideSliceTeamsItem,
			FullScreenSlideSliceHalfPagePrimary,
			FullScreenSlideSliceHalfPageItem,
			FullScreenSlideSliceBigTextPrimary,
			FullScreenSlideSliceHalfPageWithButtonOverlaysPrimary,
			FullScreenSlideSliceHalfPageWithButtonOverlaysItem,
			FullScreenSlideSliceVariation,
			FullScreenSlideSliceDefault,
			FullScreenSlideSliceEmbed,
			FullScreenSlideSliceWithVideoPopup,
			FullScreenSlideSliceBasic,
			FullScreenSlideSliceIconBoxes,
			FullScreenSlideSliceTeams,
			FullScreenSlideSliceHalfPage,
			FullScreenSlideSliceBigText,
			FullScreenSlideSliceHalfPageWithButtonOverlays,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			RichTextSlice,
			RichTextSliceDefaultPrimary,
			RichTextSliceVariation,
			RichTextSliceDefault
		};
	}
}
